In [1]:
!pip install faiss-cpu 
!pip install sentence-transformers

In [2]:
import pandas as pd 
pd.set_option('display.max_colwidth',100)

In [3]:
df=pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [4]:
df 

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel


In [8]:
from sentence_transformers import SentenceTransformer 

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df['text'].fillna('').astype(str).tolist())
vectors.shape

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

(8, 768)

In [9]:
vectors

array([[-0.00247393,  0.03626724, -0.05290457, ..., -0.09152355,
        -0.03970002, -0.04330488],
       [-0.03357266,  0.00980519, -0.03250128, ..., -0.05165466,
         0.02245887, -0.03156182],
       [-0.01865324, -0.04051313, -0.01235388, ...,  0.00610587,
        -0.07179645,  0.02773851],
       ...,
       [-0.00066459,  0.04252128, -0.05645507, ...,  0.01315472,
        -0.03183567, -0.04357663],
       [-0.03317154,  0.03252457, -0.02484838, ...,  0.01174421,
         0.05747123,  0.00571022],
       [-0.00166394,  0.00413825, -0.04597083, ...,  0.02008527,
         0.05656242, -0.00161596]], shape=(8, 768), dtype=float32)

In [10]:
dim=vectors.shape[1]

In [11]:
dim

768

In [12]:
import faiss
index=faiss.IndexFlatL2(dim) #euclidean distance
index



<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x00000150A5539130> >

In [13]:
index.add(vectors)

In [14]:
search_query="i want to buy a polo t shirt "
vec= encoder.encode(search_query)
vec.shape

(768,)

In [15]:
vec

array([ 1.26710953e-02,  1.31741827e-02, -1.28744356e-02,  2.12206189e-02,
        2.57129245e-03, -1.13254301e-02,  2.83509623e-02,  2.29298044e-02,
       -2.45132614e-02,  5.12767695e-02,  2.32123863e-02, -1.31430989e-02,
        2.67193224e-02,  5.06750718e-02,  3.24847526e-03, -2.34811064e-02,
        7.36932177e-03, -2.47090217e-02,  7.76624233e-02, -1.54065210e-02,
        1.24682151e-02, -4.42487793e-03, -2.07675528e-02,  5.24218678e-02,
       -9.16953944e-03, -3.81671935e-02,  1.95779745e-02, -9.25241411e-03,
       -3.59976813e-02,  5.77961560e-03,  4.18735072e-02, -9.89899877e-03,
       -1.43275503e-02, -2.71977000e-02,  1.18072285e-06, -7.34854024e-03,
       -2.04257928e-02, -8.89537185e-02,  3.91716091e-03, -1.71832629e-02,
       -1.28232948e-02,  9.10232589e-02, -3.56417075e-02,  2.07802001e-03,
       -8.70520528e-03, -4.35536169e-02,  5.48262298e-02,  1.28873333e-01,
       -7.61863664e-02,  8.90009291e-03, -5.79260476e-03,  2.37703230e-02,
       -2.52667125e-02, -

In [16]:
import numpy as np 
svec=np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [17]:
svec

array([[ 1.26710953e-02,  1.31741827e-02, -1.28744356e-02,
         2.12206189e-02,  2.57129245e-03, -1.13254301e-02,
         2.83509623e-02,  2.29298044e-02, -2.45132614e-02,
         5.12767695e-02,  2.32123863e-02, -1.31430989e-02,
         2.67193224e-02,  5.06750718e-02,  3.24847526e-03,
        -2.34811064e-02,  7.36932177e-03, -2.47090217e-02,
         7.76624233e-02, -1.54065210e-02,  1.24682151e-02,
        -4.42487793e-03, -2.07675528e-02,  5.24218678e-02,
        -9.16953944e-03, -3.81671935e-02,  1.95779745e-02,
        -9.25241411e-03, -3.59976813e-02,  5.77961560e-03,
         4.18735072e-02, -9.89899877e-03, -1.43275503e-02,
        -2.71977000e-02,  1.18072285e-06, -7.34854024e-03,
        -2.04257928e-02, -8.89537185e-02,  3.91716091e-03,
        -1.71832629e-02, -1.28232948e-02,  9.10232589e-02,
        -3.56417075e-02,  2.07802001e-03, -8.70520528e-03,
        -4.35536169e-02,  5.48262298e-02,  1.28873333e-01,
        -7.61863664e-02,  8.90009291e-03, -5.79260476e-0

In [18]:
distances,I=index.search(svec, k=2)

In [19]:
I 

array([[3, 2]])

In [ ]:
df.loc[I[0]]

In [ ]:
search_query